package com.Wsdl2Code.WebServices.ServiceMobile;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 7/29/2015 10:05:22 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.io.Serializable;
import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class RecommendedJobDto implements KvmSerializable, Serializable {
    
    public String jobId;
    public double predictedRankingValue;
    public boolean predictedRankingValueSpecified;
    public String recruiteeId;
    
    public RecommendedJobDto(){}
    
    public RecommendedJobDto(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("JobId"))
        {
            Object obj = soapObject.getProperty("JobId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                jobId = j.toString();
            }else if (obj!= null && obj instanceof String){
                jobId = (String) obj;
            }
        }
        if (soapObject.hasProperty("PredictedRankingValue"))
        {
            Object obj = soapObject.getProperty("PredictedRankingValue");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                predictedRankingValue = Double.parseDouble(j.toString());
            }else if (obj!= null && obj instanceof Number){
                predictedRankingValue = (Double) obj;
            }
        }
        if (soapObject.hasProperty("PredictedRankingValueSpecified"))
        {
            Object obj = soapObject.getProperty("PredictedRankingValueSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                predictedRankingValueSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                predictedRankingValueSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("RecruiteeId"))
        {
            Object obj = soapObject.getProperty("RecruiteeId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                recruiteeId = j.toString();
            }else if (obj!= null && obj instanceof String){
                recruiteeId = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return jobId;
            case 1:
                return predictedRankingValue;
            case 2:
                return predictedRankingValueSpecified;
            case 3:
                return recruiteeId;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "JobId";
                break;
            case 1:
                info.type = Double.class;
                info.name = "PredictedRankingValue";
                break;
            case 2:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "PredictedRankingValueSpecified";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "RecruiteeId";
                break;
        }
    }
    

    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
